{% set version = '<CURRENT_VERSION>' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-scworkflow-test
  version: {{ version|replace("-", "_") }}

channels:
  - conda-forge
  - bioconda

source:

  git_url: https://github.com/ruiheesi/SCWorkflow
  git_tag: continuous_deployment

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat (>= 3.0.0)
requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base ==4.1.3
    - r-biocmanager
    - r-gdata=r41hc72bb7e_0==2.19.0
    - bioconductor-complexheatmap >=2.10.0
    - bioconductor-mast >=1.20.0
    - r-rcolorbrewer >=1.1_3
    - r-seurat >=4.1.1
    - bioconductor-singler >=1.8.1
    - r-anndata >=0.7.5.2
    - r-callr >=3.7.1
    - r-colorspace
    - r-cowplot >=1.1.1
    - r-data.table >=1.14.2
    - r-dendextend
    - r-dendsort
    - r-dplyr >=1.0.9
    - bioconductor-edger >=3.36.0
    - r-future >=1.27.0
    - r-future.apply >=1.9.0
    - r-gargle >=1.2.0
    - r-ggplot2 >=3.3.6
    - r-ggpubr >=0.4.0
    - r-globals >=0.16.1
    - r-gridbase >=0.4_7
    - r-gridextra >=2.3
    - r-harmony >=0.1
    - r-hdf5r >=1.3.5
    - r-httpuv >=1.6.5
    - r-httr
    - r-jsonlite
    - r-leiden >=0.4.2
    - bioconductor-limma >=3.50.3
    - r-magrittr >=2.0.3
    - r-markdown >=1.1
    - r-pheatmap
    - r-plotly >=4.10.0
    - r-plyr
    - r-png
    - r-progressr >=0.10.1
    - r-pryr >=0.1.5
    - r-purrr >=0.3.4
    - r-quantmod >=0.4.20
    - r-reshape2 >=1.4.4
    - r-reticulate >=1.25
    - r-rlang >=1.0.6
    - r-scales
    - bioconductor-scdblfinder
    - r-statmod >=1.4.37
    - r-stringr >=1.4.1
    - r-svglite >=2.1.0
    - r-tibble >=3.1.8
    - r-tidyverse >=1.3.2
    - r-viridislite >=0.4.0
    - r-xfun >=0.32
    - r-zip >=2.2.0
    - r-harmony >=1.1.0
    - bioconductor-celldex=r41hdfd78af_1==1.4.0
  run:
    - r-base ==4.1.3
    - r-biocmanager
    - r-gdata
    - bioconductor-complexheatmap >=2.10.0
    - bioconductor-mast >=1.20.0
    - bioconductor-scdblfinder
    - bioconductor-celldex=r41hdfd78af_1==1.4.0
    - r-rcolorbrewer >=1.1_3
    - r-seurat >=4.1.1
    - bioconductor-singler >=1.8.1
    - r-anndata >=0.7.5.2
    - r-callr >=3.7.1
    - r-colorspace
    - r-cowplot >=1.1.1
    - r-data.table >=1.14.2
    - r-dendextend
    - r-dendsort
    - r-dplyr >=1.0.9
    - bioconductor-edger >=3.36.0
    - r-future >=1.27.0
    - r-future.apply >=1.9.0
    - r-gargle >=1.2.0
    - r-ggplot2 >=3.3.6
    - r-ggpubr >=0.4.0
    - r-globals >=0.16.1
    - r-gridbase >=0.4_7
    - r-gridextra >=2.3
    - r-harmony >=0.1
    - r-hdf5r >=1.3.5
    - r-httpuv >=1.6.5
    - r-httr
    - r-jsonlite
    - r-leiden >=0.4.2
    - bioconductor-limma >=3.50.3
    - r-magrittr >=2.0.3
    - r-markdown >=1.1
    - r-pheatmap
    - r-plotly >=4.10.0
    - r-plyr
    - r-png
    - r-progressr >=0.10.1
    - r-pryr >=0.1.5
    - r-purrr >=0.3.4
    - r-quantmod >=0.4.20
    - r-reshape2 >=1.4.4
    - r-reticulate >=1.25
    - r-rlang >=1.0.6
    - r-scales
    - r-statmod >=1.4.37
    - r-stringr >=1.4.1
    - r-svglite >=2.1.0
    - r-tibble >=3.1.8
    - r-tidyverse >=1.3.2
    - r-viridislite >=0.4.0
    - r-xfun >=0.32
    - r-zip >=2.2.0
    - r-harmony >=1.1.0
test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('SCWorkflow')"           # [not win]
    - "\"%R%\" -e \"library('SCWorkflow')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.
