name: Gitflow Action for R Package Development
run-name: ${{ github.actor }} now ${{ github.event_name }} to ${{ github.ref_name }}

on:
  push:
    branches: ['*', '!dev']
    
  pull_request:
    types: ['opened', 'closed']
    branches: ['main', 'release*']

jobs:
  Activating_Parser:
    uses: fnlcr-bids-sdsi/gitflow-R/.github/workflows/parser.yml@SCWorkflow
    with:
      image_to_use: "ghcr.io/nidap-community/single-cell-rna-r4:v1.0"
